### ISSUE TITLE
meditate looked like it allowed meditation of a card in discard

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#690] opened 2021-09-23 19:54 UTC
this was in my game vs dYnkYn

**Comment by 5H4Z** [comment] 2021-09-25 06:45
If you have a screenshot, the event messages for meditation now say where the card was meditated from, which should help to confirm what is happening. Through a lot of clicking, the only think I see that is a bit like what you have described, is after you choose to meditate a card from deck or from your hand, when the prompt "Choose a die to change" appears, the cards in your hand, in your discard pile and your PB are not greyed out. It actually means that you can change to a different card from your hand, but I was not able to select a card from discard or my PB.

**Comment by danj3000** [comment] 2021-09-25 08:40
It was your new message that showed the problem 👍
This might be an edge case due to poor cleanup of the previous action. the particle shield had just been used in a reaction the turn before. Then the player said they could only select that card during meditation.
A weird one for sure

**Comment by 5H4Z** [comment] 2021-09-25 22:17
Reproduced. Definitely looks like an edge case due to Particle Shield clean up from the turn immediately prior, as I didn't get this happening if I played Particle on one of my turns and then on my next turn I meditated: 
![image](https://user-images.githubusercontent.com/89332227/134787172-78ed4cd6-601d-41a0-98e1-08333e2858d6.png)
The person meditating can work around this by selecting a card from hand or a card on their spellboard instead of selecting a die. Once they select something else, and perhaps cancel the meditation, it appears that the clean up has occurred correctly, as then the Particle Shield is not selected.

**Comment by 5H4Z** [comment] 2021-09-25 22:31
This bug does not occur consistently. For example, slight modifications of the setup, e.g. the Butterfly Monk attacks or one Shadow Spirit is not destroyed due to the Mist Typhoon, did not have the same result when Victoria meditated on the following turn.

**Comment by 5H4Z** [comment] 2021-10-03 21:40
This should be fixed with the initialisation of selected cards. We can open a new ticket if this is spotted again.

**Closed by 5H4Z** 2021-10-03 21:40 UTC
Labels: bug
